### ISSUE TITLE
Regarding the LTS release

### ISSUE THREAD

**Issue by JatinBatra-Aviz** [clicon/cligen#100]
Hey Guys,
Are you guys labelling any release as, LTS ?
Im currently working with 4.6.0 and want to upgrade the cligen to as new as possible.
If community have not marked LTS yet, which stablest version should I go with?

**Comment by olofhagsand** [comment]
No, releases are not marked with LTS.
The latest release is 6.3.0, https://github.com/clicon/cligen/releases/tag/6.3.0
6.4.0 is planned for October, the version of master is 6.4.0.PRE which is not a proper release.
Therefore, if you are want a stable release you should go with the latest which is 6.3.0.

**Comment by JatinBatra-Aviz** [comment]
Thanks for the clarification and quick response.
