### ISSUE TITLE
Space after comma not allowed in pre-function parsing

### ISSUE THREAD

**Issue by pprindeville** [clicon/cligen#101]
I have the following `.cli` file:

```
...
    43	no("Delete") {
    44	    server("Server")
    45		<name:string tnsr_expand_dbvar("candidate", "/netgate-radius:radius-client/client/servers=%s/name")>("Name of server"),
    46	            tnsr_cli_del("/netgate-radius:radius-client/client/servers=%s", "name");
    47	}
...
```

and it fails to parse with:

```
/usr/lib/x86_64-linux-gnu/tnsr/clispec/radius.cli:45: Error: syntax error: at or before: ' '
```

i.e. the space after the comma between the arguments to the pre-function.

I also tried putting spaces before the after the `(`, before the `,`, and before the `)` and those also failed.

**Comment by olofhagsand** [comment]
Removed explicit whitespaces in lex/yacc rules.
Please verify

**Comment by pprindeville** [comment]
This seems to fix it.
