### ISSUE TITLE
CLIGEN segmentation fault in V 6.2

### ISSUE THREAD

**Issue by Dorababupc** [clicon/cligen#105]
Hello guys, 

 I used to use cligen R 4.2.0 in one of my projects, that I used to run on the  box with these specs:
 
     admin@sonic:~/dorababu/2.0$ ldd --version
     ldd (Debian GLIBC 2.31-13+deb11u5) 2.31

     admin@sonic:~/dorababu/2.0$ uname -r
     5.10.0-8-2-amd64

Everything was working fine then. But when I changed the cligen to R 6.2.0, I was facing the below error when I am trying to launch my application using cligen engine.

     sonic INFO kernel: [5618339.188981] fmcli[742764]: segfault at 4 ip 00007f423b1f95b4 sp 00007ffd7f7f16d8 error 6 in libcligen.so.6.2[7f423b1f2000+4e000]
     
     
Any thoughts regarding this. Thank you for your time.

**Comment by olofhagsand** [comment]
No, not known. Need more info.
Preferably a stack trace. Or at least a method to provoke it.
Remember to reinstall+recompile everything.

**Comment by Dorababupc** [comment]
Yes, I have tried reinstalling and recompiling everything. 

These three functions are invoked.

1. cligen_ph_active_set_byname 
2. cligen_ph_find
3. cligen_pt_head_active_set

1, 2 functions are defined inside cligen_pt_head.c and 3 inside cligen_handle.c

    
    cligen_ph_active_set_byname(h, "configmode");
    
     int  cligen_ph_active_set_byname(cligen_handle h, char *name)
    {
    system("sudo touch /tmp/debug101");
    pt_head *ph = cligen_ph_find(h, name);
    cligen_pt_head_active_set(h, ph);
    system("sudo touch /tmp/debug107");
    return 0;
    }
    
    pt_head * cligen_ph_find(cligen_handle h, char  *name)
    {
    char *phname;

    pt_head *ph = NULL;
    system("sudo touch /tmp/debug102");
    while ((ph = cligen_ph_each(h, ph)))
        if ((phname = cligen_ph_name_get(ph)))
            if (strcmp(phname, name) == 0)
                return ph;
    return ph;
     }

     int  cligen_pt_head_active_set(cligen_handle h, pt_head *ph)
     {
    system("sudo touch /tmp/debug105");
    struct cligen_handle *ch = handle(h);
    system("sudo touch /tmp/debug106");
    ch->ch_pt_head_active = ph;
    return 0;
    }


 Here are the files created inside the /tmp
 
      debug101
      debug102
      debug105
      
      
And then the seg fault. So, ultimately it is stucking inside cligen_pt_head_active_set function.

I know I have used very dumb way of debugging, please feel free to ask me for any further clarifications. 

@olofhagsand

**Comment by Dorababupc** [comment]
Hello @olofhagsand 

I have backtracked the issue and found that I was manipulating the cligen_handle and making it NULL before giving it to cligen_ph_active_set_byname function call. So, everything from there is going unexpected. I have sorted this in my code and it is working very fine now. 

So, you can ignore this issue. Thank you so much for your time @olofhagsand
