### ISSUE TITLE
A question about a callback for ?

### ISSUE THREAD

**Issue by khromenokroman** [clicon/cligen#109]
Example of the cligen plugin
```
constexpr const char *plug_name = "cligen-plug-test";

extern "C" int mycallback(cligen_handle h, cvec *cvv, cvec *argv) {
    (void) h;
    cg_var *cv = nullptr;
    char buf[64];
    int pid;
    int ret;
    int status;

    if (argv == nullptr)
        return 0;
    char *python_interpreter_path = (char *) "/usr/bin/python3"; 
    char *python_program_path;
    if ((pid = fork()) == 0) {
        while ((cv = cvec_each1(cvv, cv)) != nullptr) {
            if (cv_const_get(cv))
                continue;
            cv2str(cv, buf, sizeof(buf) - 1);
            setenv(cv_name_get(cv), buf, 1);
        }

        python_program_path = buf;
        char *args[] = {python_interpreter_path, python_program_path, nullptr};
        execv(python_interpreter_path, args);
        perror("execv");
        exit(0);
    }

    if (waitpid(pid, &status, 0) == pid)
        ret = WEXITSTATUS(status);
    else
        ret = -1;
    return ret;
}

static clixon_plugin_api api;

clixon_plugin_api *clixon_plugin_init(clixon_handle h) {
    (void) h;
    printf("Load plugin: %s ver: %s\n", plug_name, APP_EXT_VERSION);
    strcpy(api.ca_name, plug_name);
    return &api;
}
```
in *.cli
```
run_roma_script("run script python3") {
    <var:string>("Path to script"), mycallback("myarg");
}
```

in cli
now when you click on ? it happens like this
```
user@user/> run_roma_script 
  <var>                 Path to script 
```
and I would like that when you click on ? some of my logic was executed, for example, he displayed a list of scripts that are in the directory or, for example, a list of interfaces that are in the system

is it possible to somehow hang a callback for an operation ?

Need help :)

Thanks

**Comment by olofhagsand** [comment]
Yes, this is the "expand" functionality. 
See section 3.11 here: https://github.com/clicon/cligen/blob/master/cligen_tutorial.pdf
There are also clixon-specific functions, such as https://github.com/clicon/clixon/blob/a1badc312eafdf0300558eaed46905406bf336fa/example/main/example_cli.cli#L74

**Comment by khromenokroman** [comment]
> Yes, this is the "expand" functionality. See section 3.11 here: https://github.com/clicon/cligen/blob/master/cligen_tutorial.pdf There are also clixon-specific functions, such as https://github.com/clicon/clixon/blob/a1badc312eafdf0300558eaed46905406bf336fa/example/main/example_cli.cli#L74

Thank you very much, I didn't notice

**Comment by khromenokroman** [comment]
my plugin for cligen

```
extern "C" int get_mac(cligen_handle h, cvec *cvv, cvec *argv, cvec *commands, cvec *helptexts){
    cvec_add_string(helptexts, NULL, "0a:00:27:00:00:00");
    return 0;

extern "C" int roma_test(clixon_handle h, cvec *cvv, cvec *argv) {

    cvec *cvv2 = nullptr;

    cvv2 = cvec_append(clicon_data_cvec_get(h, "cli-edit-cvv"), cvv);
    cvec_print(stderr, cvv2);

    if (cli_dbxml(h, cvv2, argv, OP_REPLACE, nullptr) < 0) {
        if (cvv2)
            cvec_free(cvv2);
        return -1;
    }
    return 0;
}
}

before changing the *.cli file (default)
```
set("Команда конфигурирования") {
    @datamodel, roma_test();
        log-level ("Установка уровня логирования"){
       error("Ошибка");
       warning("Предупреждение");
       info("Инфо");
       debug("Дебаг");
    }

}
```
```
user@user/> set system interface management mgmt1 ?
  <cr>
  allow-access          Разрешенные сервисы                                                                                     
  description           Текстовое описание интерфейса                                                                  
  enabled               Состояние интерфейса                                                                                   
  ipv4                  Настройка IPv4 адресации                                                                                
  mac-address           Настройка мак-адреса на интерфейсе управления
```

add string (not replace) in *.cli
```
set system interface management mgmt1 mac-address <ifname:string get_mac()> @datamodel, roma_test();
```
```
user@user/> set system interface management mgmt1 ?
  mac-address
```
why is it that if I add my own implementation, the data from YANG disappears?

**Comment by khromenokroman** [comment]
> Yes, this is the "expand" functionality. See section 3.11 here: https://github.com/clicon/cligen/blob/master/cligen_tutorial.pdf There are also clixon-specific functions, such as https://github.com/clicon/clixon/blob/a1badc312eafdf0300558eaed46905406bf336fa/example/main/example_cli.cli#L74

I still don't understand what I said above, is this how it should be, or is this a mistake?

**Comment by olofhagsand** [comment]
(This is a clixon question)
If I understand you correctly, you have two rules:
```
set  @datamodel ...
set system interface management mgmt1 mac-address <ifname:string get_mac()> @datamodel,
```
Where the first set statement is for most commands, but you want to override it with the second, is that correct?

If so, I am not sure that would work.

The "set @datamodel" syntax is actually on an abstraction layer that generates lower-level rules. You may want to see the lower-level rules by starting clixon_cli with t s he -G option. There you see some more elaborate syntax. You could start the cli with this concrete syntax and you like, and could edit it in detail.
However, as soon as the YANG changes you would need to regenerate it.
Hope this clarifies some.
