### ISSUE TITLE
Log in plugin cligen

### ISSUE THREAD

**Issue by khromenokroman** [clicon/cligen#110]
```
clicon_log(LOG_ERR, "[%s]-[%s] Template for NetConf request is not correct, can not find substring <name>sample</name>", FQDN::plug_name, FQDN::class_name);
```

Hello
if I do this, then my output is reflected on the user's console, can I make it written to the log?

and another question is, if I want to change the mode, for example, logging clixon-backend.service, will this apply to cligen plugins?

**Comment by olofhagsand** [comment]
(This is a clixon question).
It depends on where you have directed the log. 
As described here, https://clixon-docs.readthedocs.io/en/latest/cli.html#command-line-options, the log is default directed to stderr.
If you want it written to the syslog, you can do this by starting the cli with option -l s.
You can also use the clixon_log_init() API function where the `flags` field sets where the log is directed to, possibly several.
If you want it unconditionally to syslog, you can call syslog() directly.
