### ISSUE TITLE
Best way to implement output pipes?

### ISSUE THREAD

**Issue by SCadilhac** [clicon/cligen#19]
Hello,

What would be the best way to implement output modifiers, e.g. `show something | include bla` to filter out the output of the given command?
Other example, but probably different implementation: `show configuration | display json`, which would totally change the output (produce a JSON output of the configuration in that case).

Thanks,
Sylvain

**Comment by olofhagsand** [comment]
Q: would "bla" be any executable program (eg a script?)
I made some experiments with this a while back.
One way is to make the shell do it, eg unix pipes. But I couldn't make that to work in an acceptable "embedded" way.
Another way is to "embed" the pipe command, eg inside cligen.
An issue is how you specify the commands in the pipe commands. They would be the same I assume for all commands in the tree. That is, "include bla" and "display json" would be available everywhere? You would need to specifiy them somewhere,such as in a "plugin" dir with "pipeline" programs that are available for an application.
You would also want to have longer pipes, eg show configuration | display json | count.

**Comment by SCadilhac** [comment]
In my first example, "bla" is a just a text, even a regexp, to filter out the output, so `include` is more or less an alias for `grep` (this comes from classical Cisco CLI).
I was indeed thinking about doing all the processing within cligen (no call to external program).

You are right, the pipe commands would have to be available for all commands within a mode.
Note that the two examples, `include` and `display` are rather different to implement. The first one is just a modifier of the output of the previous command and could be chained indeed (just like UNIX-like piping).
The `display` thing is special. It comes from Juniper-like CLIs. It should be called in first position of the pipe chaining only. It doesn't process the output from the previous command but is rather a generic parameter to the initial command.

**Comment by SCadilhac** [comment]
Hi @olofhagsand, yes indeed the main use case is stdin/stdout chaining. The display modifier could be a parameter of the previous command. Or each callback could always generate both XML and human-readable outputs.

**Comment by olofhagsand** [comment]
A first version is finally implemented, see cligen-.tutorial  section 2.8 and https://clixon-docs.readthedocs.io/en/latest/cli.html#output-pipes
