### ISSUE TITLE
CLI syntax help

### ISSUE THREAD

**Issue by sharmadeepak29** [clicon/cligen#22]
Hello,
I am trying to write a cli using your cligen module. I am facing a issue.
Below is my syntax:-
------------------------------------
aa
{
  [bb]
  [cc]
  [dd];
}
---------------------------------------
now on cli prompt output:-
cli>aa bb cc dd --- valid output
cli>aa cc dd bb --- not a valid output

I am wondering why i am not able to give the second command.
Is there a restriction on order of parameters at the same level. If yes, I would like to have an order independent command processing. Can we have a syntax which will help in in achieving my goal.

when i  do 
cli> aa cc ?
it should show both 
bb
dd

as help ouptut.

Thanks and Regards,
Deepak Sharma

**Comment by olofhagsand** [comment]
Sharma,
your syntax can be written as:
```
  aa {
    [bb] [cc] [dd];
  }
```
Since the [bb][cc][dd] is in sequence, they must appear one after the other.
Valid strings are therefore: "aa", "aa bb", "aa bb cc", "aa bb cc dd", "aa bb dd", "aa cc", "aa cc dd", and "aa dd".
An alternative is:
```
  aa {
    [bb]; [cc]; [dd];
  }
```
where valid strings are "aa bb"; "aa cc" and "aa dd".

If you want a list, eg (*) or (+) they can not be implemented with this basic syntax. Instead you could use the tree operator '@', for example:
```
  a @list;
  treename="list";
  [bb] [cc] [dd] @list;
```
or, with a terminating condition:
```
  a @list;
  treename="list";
  [bb] [cc] [dd];{ 
          @list;
  }

```

**Comment by sharmadeepak29** [comment]
Hello Olof,

Thank you for your response.
However, there one issue with that, I can give the same parameter again and again in command.
I am looking for a CLI to be order independent.
1. Can we have a CLI with no dependence on order if the parameters are at the same level?
for example:-
aa{
[bb]
[cc]
[dd];
}
Valid commands below:-
cli> aa bb ? 
<cr>
cc  -
dd -
cli> aa cc ?
<cr>
bb
dd
cli> aa dd ?
<cr>
bb 
cc

2. Is there a way to display only those parameters which have not been used in the command till now?    
And if there is no such syntax possible would you like to take it as an enhancement or let me know how I can enhance the code to cater to my requirements. I would love to contribute to your work,

**Comment by olofhagsand** [comment]
No, not in a straight-forward way. I dont know how to do that in a BNF or context-free grammar or regexp in general?  Ie, from a set of words accept all combinations of them occuring exactly once. The closest I can think of is members of a "set". 
You are welcome to contribute but it would have to use some new syntax. Preferably if you can find some notation from some other formal language or tool.

The only solution I can find is something like:
```
aa {
  bb{
    cc dd;
    dd cc;
    }
  cc{
    bb dd;
    dd bb;
  }
  dd{
    bb cc;
    cc bb;
  }
}
```
which is the same as:
```
aa {
  bb (cc dd|dd cc);
  cc (bb dd|dd bb);
  dd (bb cc|cc bb);
}
```
or:
```
aa (bb (cc dd|dd cc) | cc (bb dd|dd bb) |  dd (bb cc|cc bb));
```

I am a little curious: what is the use-case for this?

**Comment by olofhagsand** [comment]
New "sets" feature added, see:
https://github.com/olofhagsand/cligen/commit/ed1997a0c335f49073d287a2469a28d39540e791

Example: aa @{ bb; cc; dd; }

**Comment by gopiKrishnaPuligundla** [comment]
Hi Olof , 
is there a complete guide on different options cligen provides and how to use it , what ever pdf available in git repository doesn't discuss all available options

**Comment by olofhagsand** [comment]
CLIgen has several options that can be set programmatically using the API here:
https://github.com/clicon/cligen/blob/master/cligen_handle.h
Most of them are not documented in the cligen-tutorial pdf.
The easiest would be to to add them there. 
Thanks for pointing that out.
