### ISSUE TITLE
Check if cg_obj is optional

### ISSUE THREAD

**Issue by owenlejeune** [clicon/cligen#38]
Is there anyway currently to determine if a cg_obj is an optional?  I am currently implementing a command to print the full command tree and would like to avoid printing all permutations for optionals.  For example, with the tree
```
aa {
    bb {
        [
           [cc]
           [dd]
        ]
        ee;
    }
}
```
I would like to get the output
```
aa bb cc
aa bb dd
aa bb ee
```
but am currently getting
```
aa bb ee
aa bb cc ee
aa bb cc dd ee
aa bb dd ee
aa bb dd cc ee
```

If there is some way I could determine that `cc` and `dd` are optionals it would make this much easier.

**Comment by olofhagsand** [comment]
Interesting!
The thing is that options [] / | and grouping () are secondary constructs that are just mapped to primary syntax constructs on the form: 
```
  aa bb ee;
  aa  bb cc ee;
```
etc.
One could have a flag saying that these "cc" and "dd" are elements that have been generated from options. 
Would that help?
Otherwise I have considered reimplementing cligen with options and grouping as first class objects, since the current method is (1) not scalable; and (2) does not allow for "sets". But that would be a major undertaking.
Also, a minor detail, in your example, you have [[cc][dd]]. I think that is equivalent to [cc][dd].

**Comment by owenlejeune** [comment]
A flag on those elements would be a huge help! I have been attempting a solution by trying to parse back through the tree (eg. deciding if `dd` were an optional based on it being a child of both `bb` and `cc`), but have not been able to come up with a working solution.  Would that flag be something that's relatively easy to implement?

**Comment by olofhagsand** [comment]
Yes, very easy. But I am not sure it would cover more complex cases. That is, all it would say would be that this node is "generated from some optional statement", not exactly what that statement would look like.

**Comment by owenlejeune** [comment]
I think for my current use case and implementation a simple flag like that would be all I would need.

**Comment by olofhagsand** [comment]
I had a look and run into some problems. For example, in the below, which would you consider as optional?
```
  aa (xx|yy);
  bb [xx|yy];
  cc (xx);
  dd [xx];
```
the first one (aa) is most troublesome since it is either xx or yy (exactly one).

**Comment by owenlejeune** [comment]
My .cli files are setup using only `[]` for optionals so flagging those would be most useful.   I have scenarios such as
```
ww {
    (
        [xx]
        [yy]
        [zz]
    );
}
```
where the output would need to be
```
ww xx
ww yy
ww zz
```
Not sure how flagging `aa` and `cc` in your example would affect that.

**Comment by owenlejeune** [comment]
Any more thoughts around this?

**Comment by olofhagsand** [comment]
Sorry. Yes, there is some code in a patch here:
https://github.com/olofhagsand/cligen/commit/597e7556859f5a6573881de704e92ad1bf0d48d7
where a flag CO_FLAGS_OPTION is set in some of these circumstances.
It is not perfect but works in some situations. Maybe you can test it out?
You can test for it by: `co_flags_get(co, CO_FLAGS_OPTION)`

(To be perfectly honest I committed it as part of another commit by mistake, and then forgot about it.)

**Comment by owenlejeune** [comment]
I've begun integrating and testing these fixes but I've noticed a few issues.  I have the following tree in my `.cli` file:
```
aa {
  bb, cb(); {
    dd {
       ee<ee-var:string> {
    }
    [
      [ff<ff-var:string>]
      [gg<gg-var:string>]
    ]
    hh<hh-var:uint64>, cb();
  }
}
```
I have added debug statements to `cligen_parse.y` when the CO_FLAGS_OPTION flag is set.  I would expect this flag to only be set on `ff/ff-var` and `gg/gg-var` (the only nodes in []).  However, I see the output
```
ctx_pop_add line 778 : Setting CO_FLAGS_OPTION flag - ff-var
ctx_pop_add line 778 : Setting CO_FLAGS_OPTION flag - gg-var
ctx_pop_add line 778 : Setting CO_FLAGS_OPTION flag - gg-var
ctx_pop_add line 778 : Setting CO_FLAGS_OPTION flag - bb
ctx_pop_add line 778 : Setting CO_FLAGS_OPTION flag - ff-var
ctx_pop_add line 778 : Setting CO_FLAGS_OPTION flag - gg-var
ctx_pop_add line 778 : Setting CO_FLAGS_OPTION flag - gg-var
```
This could be my misunderstanding, but why would `ff` and `gg` not have the CO_FLAGS_OPTION flag set?  And why does `bb` have this flag set if it is not an optional?
