### ISSUE TITLE
Case-Insensitive Command Matching

### ISSUE THREAD

**Issue by owenlejeune** [clicon/cligen#46]
Given the commands tree
```
Aa {
  Bb, cb();
}
```
I would like to able to enter commands without matching case.  Currently, entering the command `aa bb` results in an "Unknown command" error. I would like to be able to enter the command `aa bb` and have it execute successfully.

**Comment by olofhagsand** [comment]
Added case-insensitive command matching
  * See [Case-Insensitive Command Matching](https://github.com/clicon/cligen/issues/46)
  * To set cligen ignore case, you must call `cligen_caseignore_set(h, 1)`
  * Note applications using cligen (eg clixon) may have case-sensitive code despite setting this
  
Please verify
