### ISSUE TITLE
Need to add the possibility to use anchors around patterns

### ISSUE THREAD

**Issue by vsharapov-udelphi** [clicon/cligen#51]
Need to add the possibility to use anchors (^ and $) around patterns (regexp) which is part of POSIX.
Now https://github.com/clicon/cligen/blob/master/cligen_regex.c#L91 always wraps any regexp with ^(...)$

**Comment by olofhagsand** [comment]
I have patched cligen and clixon for both stripping existing "^$" as well as conditionally skip escape of "$". I have also added the openconfig testcase to test/test_pattern.sh.
If possible, please verify that it works now.
