### ISSUE TITLE
Help with hidden commands

### ISSUE THREAD

**Issue by sergio-salas** [clicon/cligen#54]
Hello,

I'm trying to develop a CLI using cligen, and I would like to have some hidden (non-documented) commands. I have read in the tutorial that it's possible using the keyword "hide". However I have not managed to make it work when the command contains variables (parameters).

The cligen_tutorial example contains a simple hidden command. It is possible to reproduce the issue if the definition of the command in the file "tutorial.cli" is changed as shown below:

#secret,hide,secret("message");
secret("Help text") <param:string>,hide,secret("message");

Then the parameter is hide but not the command.

Am I doing something wrong?

Thanks and Regards,
Sergio

**Comment by olofhagsand** [comment]
This would work:
```
#secret,hide,secret("message");
secret("Help text"),hide{
   param:string,secret("message");
}
```
