### ISSUE TITLE
Get the expanded string of entire command executed even if entered string is partial

### ISSUE THREAD

**Issue by DeekshaBhandary** [clicon/cligen#65]
```
cli> show list1 ?
value1
data1
string1
cli> show list1 s  <Enter>
```
cv_string_get(cvec_i(cvv, 0));   this method returns "show list1 s" instead of "show list1 string1" in the  above case
Should be able to retrieve the entire string

**Comment by olofhagsand** [comment]
Added a replacement of the cvv[0] cmd parameter from the _original_ string to the _expanded_ string.
However it turned out the expanded string depended on `excludekeys` settings and needed to be reverted.
Need somewhat larger take and will have to wait.

**Comment by olofhagsand** [comment]
There is now a solution to this issue.
To get the behavior requested in this ticket, you need to call: `cligen_expand_first_set(h,1)`
Please see also cligen_tutorial Section 6.1
Please verify the solution

**Comment by olofhagsand** [comment]
To clarify, to test it, you need to initialize it properly, such as call cligen_expand_first_set(cli_cligen(h), 1) at some point in main() in apps/cli/cli_main.c and recompile. No specific config option is added yet.

**Comment by DeekshaBhandary** [comment]
Issue has been fixed.
