### ISSUE TITLE
expansion does not work for keywords when another tree is referenced in the .cli file

### ISSUE THREAD

**Issue by DeekshaBhandary** [clicon/cligen#73]
Issue is seen when redundant keywords are present in the referenced tree at the same hierarchy

consider tree syntax : 
**file:op.cli**
treename= "op";
show { 
word1;
word2;
}

**file : test.cli**
show {
word3;
word4;
}
@op;

```
cli: op> show <PRESS ?>
word1
word2
cli :op>
```
```
cli: cfg><PRESS ?>
show
show                    <------------------ duplicate keywords
cli: cfg> show <PRESS ?>     <-------------------no suggestion are seen
```
Expected behaviour :
```
cli: cfg> show <PRESS ?>
word1
word2
word3
word4
cli: cfg>

**Comment by olofhagsand** [comment]
Related to https://github.com/clicon/clixon/issues/301 but somewhat larger in that not only duplicate keywords but also no expanded suggestions are seen.
As with #301 it worked in 5.3 but is broken in 5.4 and 5.5

**Comment by DeekshaBhandary** [comment]
Issue is solved. Thank You
