### ISSUE TITLE
Compiling with `-DNDEBUG` results in failure of test applications.

### ISSUE THREAD

**Issue by theonemcdonald** [clicon/cligen#76]
I stumbled onto an interesting bug related to the use of `asserts()` and the `-DNDEBUG` compiler flag. I have been experimenting with using CMake to build Cligen (you can find that attempt here: https://github.com/theonemcdonald/cligen/tree/cmake).

The CMake default CFLAGS for each build type are as follows:
```
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO: -O2 -g -DNDEBUG
CMAKE_C_FLAGS_MINSIZEREL: -Os -DNDEBUG
```
The failure case can be readily observed by compiling Cligen with `-DNDEBUG` and running the `cligen_hello` test application. In this case, typing `hello<tab><tab><tab>...` causes Cligen to just keep repeating the `hello` keyword:

![image](https://user-images.githubusercontent.com/3102039/157499170-1d223da1-d6eb-45f3-a498-94d65c5c963c.png)

building without `-DNDEBUG` yields the correct behavior:

![image](https://user-images.githubusercontent.com/3102039/157499583-0388832e-15aa-49a3-aa1e-68bf922ba571.png)

The issue appears to be related to an `assert()` call having undesired side-effects.

After consulting with Olof, we determined this to be a likely culprit that should be explored further:

https://github.com/clicon/cligen/blob/9e6f5ad5568d3fdbb1f9e0a585bffbff0204c700/cligen_match.c#L238

```
cligen_match.c:239:18: warning: variable 'levels' is uninitialized when used here [-Wuninitialized]
    if (level >= levels)
                 ^~~~~~
cligen_match.c:236:15: note: initialize the variable 'levels' to silence this warning
    int levels;
              ^
               = 0
```

**Comment by olofhagsand** [comment]
Should be fixed by the patch, please verify

**Comment by theonemcdonald** [comment]
Verified. This looks good now.
