### ISSUE TITLE
Is there any way to read from the file , instead of reading from the stdin

### ISSUE THREAD

**Issue by JatinBatra-Aviz** [clicon/cligen#95]
Hey Guys, 
Im creating a CLI Interface, where I might need to read from the existing config file, instead of reading from the stdin. Currently the application calls the `cligen_loop`  function to read from the user stdin and execute commands.

Version used:  4.6.0

**Comment by olofhagsand** [comment]
From the clixon documentation, there are several methods, see: 
https://clixon-docs.readthedocs.io/en/latest/cli.html#running-cli-scripts
which I think all could be adjusted to a cligen context.

**Comment by JatinBatra-Aviz** [comment]
Thanks I'll take a look into it and get back to you

**Comment by JatinBatra-Aviz** [comment]
This helped, while trying to  read the config file and then read from the user stdin in the same process,
It's available on my platform GNU/Linux.

```
    int tempStdin=dup(fileno(stdin));
    dup2(fileno(fp),fileno(stdin));

    cligen_loop(h); // this read from the file 

    dup2(tempStdin,fileno(stdin));
    cligen_exiting_set(h,0); // reseting <--- do I need to call any additional functions? or this seems fine ?

    if (cligen_loop(h) < 0) // starts reading from the stdin
	goto done;
```

**Comment by olofhagsand** [comment]
@JatinBatra-Aviz I dont understand the question. cligen_exiting_set(h,1) provides a non-direct way of exiting the event loop. That is, from a callback or somewhere. Setting it back to 0 is not really defined. I think there is something else you are after?

**Comment by JatinBatra-Aviz** [comment]
Yes, I was hoping for the cli to read from a file and then give the prompt to the user in the same process. In order to do so , im calling the `cligen_loop` twice, once for reading from file and after that reading from the standard input
```
1. redirect stdin to read from the file. 
2. read from file using cligen_loop.
3. redirect the stdin to read from the user input.
4. read from the standard input again by using cligen_loop.
```

before step number 4, if I don't do. `cligen_exiting_set(h,0)` , I won't be able to use the cligen_loop as flow returns as soon as we call cligen_loop function.

**Comment by olofhagsand** [comment]
Yes, that is correct, if you want to exit one and start a new, that is a way to do it.
However, not in the comment of the function:
` You probably should copy this function and make your own main event loop`
It is really just example code.

**Comment by JatinBatra-Aviz** [comment]
Ok. That makes sense. I'll come up with something taking inspiration from `cligen_loop`
Thanks for the help. You can close this conversation.

Thanks again.
