### ISSUE TITLE
Display pipe command fails

### ISSUE THREAD

**Issue by JohannesGarm** [clicon/cligen#98]
```
root@nsolab-02[/]# show devices device crpd1 config configuration policy-options as-path-group | display json
Aug 17 13:07:15: clixon_xml_parseerror: 193: XML error: xml_parse: line 0: syntax error: at or before: crpd1: XML parse error
cligen_eval_pipe_pre child retval:-1
```

**Comment by olofhagsand** [comment]
Pipes in 6.3.0 were immature and there have been multiple issues. 
Hopefully this now works, can you please verify?

**Comment by JohannesGarm** [comment]
Now I am getting memory allocation errors so it would seem I might have to upgrade my host VM to test it properly :)

**Comment by olofhagsand** [comment]
@JohannesGarm is this still valid? If not, please close issue

**Comment by JohannesGarm** [comment]
It appears to be working again - closing the issue
